// Generated by `pnpm tokens:build` from tokens/anvil.tokens.json (pulled from Figma). Do not edit.
export const exportedAt = "2026-10-02T12:17:54.425Z" as const

export const colorGroups = [
  {
    "title": "Background",
    "tokens": [
      {
        "figma": "background/accent",
        "cssVar": "--accent",
        "description": "shadcn --accent. Hover and selected rows in menus and lists.",
        "light": {
          "hex": "#ebebeb",
          "ref": "colors/neutral/80"
        },
        "dark": {
          "hex": "#4d4d4d",
          "ref": "colors/neutral/30"
        }
      },
      {
        "figma": "background/default",
        "cssVar": "--background",
        "description": "shadcn --background. Page background.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        }
      },
      {
        "figma": "background/disabled",
        "cssVar": "--background-disabled",
        "description": "Disabled control fill.",
        "light": {
          "hex": "#f5f5f5",
          "ref": "colors/neutral/90"
        },
        "dark": {
          "hex": "#737373",
          "ref": "colors/neutral/40"
        }
      },
      {
        "figma": "background/inverse",
        "cssVar": "--background-inverse",
        "description": "Inverse surface (tooltips, dark chips).",
        "light": {
          "hex": "#0d0d0d",
          "ref": "colors/neutral/black"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        }
      },
      {
        "figma": "background/medium",
        "cssVar": "--background-medium",
        "description": "Medium-emphasis surface (e.g. toggle track).",
        "light": {
          "hex": "#b2b2b2",
          "ref": "colors/neutral/60"
        },
        "dark": {
          "hex": "#737373",
          "ref": "colors/neutral/40"
        }
      },
      {
        "figma": "background/muted",
        "cssVar": "--muted",
        "description": "shadcn --muted. Muted surfaces, table stripes, skeletons.",
        "light": {
          "hex": "#f5f5f5",
          "ref": "colors/neutral/90"
        },
        "dark": {
          "hex": "#292929",
          "ref": "colors/neutral/20"
        }
      }
    ]
  },
  {
    "title": "Foreground",
    "tokens": [
      {
        "figma": "foreground/default",
        "cssVar": "--foreground",
        "description": "shadcn --foreground. Default text and icons.",
        "light": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        }
      },
      {
        "figma": "foreground/disabled",
        "cssVar": "--foreground-disabled",
        "description": "Disabled text and icons.",
        "light": {
          "hex": "#8c8c8c",
          "ref": "colors/neutral/50"
        },
        "dark": {
          "hex": "#4d4d4d",
          "ref": "colors/neutral/30"
        }
      },
      {
        "figma": "foreground/inverse",
        "cssVar": "--foreground-inverse",
        "description": "Text on inverse.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        }
      },
      {
        "figma": "foreground/link",
        "cssVar": "--foreground-link",
        "description": "Link text.",
        "light": {
          "hex": "#0c3bca",
          "ref": "colors/blue/40"
        },
        "dark": {
          "hex": "#367dff",
          "ref": "colors/blue/60"
        }
      },
      {
        "figma": "foreground/muted",
        "cssVar": "--muted-foreground",
        "description": "shadcn --muted-foreground. Secondary text.",
        "light": {
          "hex": "#4d4d4d",
          "ref": "colors/neutral/30"
        },
        "dark": {
          "hex": "#b2b2b2",
          "ref": "colors/neutral/60"
        }
      },
      {
        "figma": "foreground/on-accent",
        "cssVar": "--accent-foreground",
        "description": "shadcn --accent-foreground. ",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/default"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/default"
        }
      },
      {
        "figma": "foreground/on-card",
        "cssVar": "--card-foreground",
        "description": "shadcn --card-foreground. ",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/default"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/default"
        }
      },
      {
        "figma": "foreground/on-popover",
        "cssVar": "--popover-foreground",
        "description": "shadcn --popover-foreground. ",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/default"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/default"
        }
      },
      {
        "figma": "foreground/on-sidebar",
        "cssVar": "--sidebar-foreground",
        "description": "shadcn --sidebar-foreground. ",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/default"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/default"
        }
      },
      {
        "figma": "foreground/on-sidebar-accent",
        "cssVar": "--sidebar-accent-foreground",
        "description": "shadcn --sidebar-accent-foreground. ",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/on-accent"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/on-accent"
        }
      },
      {
        "figma": "foreground/on-sidebar-primary",
        "cssVar": "--sidebar-primary-foreground",
        "description": "shadcn --sidebar-primary-foreground. ",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "foreground/subtle",
        "cssVar": "--foreground-subtle",
        "description": "Tertiary text and placeholders.",
        "light": {
          "hex": "#737373",
          "ref": "colors/neutral/40"
        },
        "dark": {
          "hex": "#8c8c8c",
          "ref": "colors/neutral/50"
        }
      }
    ]
  },
  {
    "title": "Surfaces",
    "tokens": [
      {
        "figma": "surface/card",
        "cssVar": "--card",
        "description": "shadcn --card. Card surfaces.",
        "light": {
          "hex": "#ffffff",
          "ref": "background/default"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "background/default"
        }
      },
      {
        "figma": "surface/popover",
        "cssVar": "--popover",
        "description": "shadcn --popover. Menus, popovers, tooltips.",
        "light": {
          "hex": "#ffffff",
          "ref": "background/default"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "background/default"
        }
      },
      {
        "figma": "surface/sidebar",
        "cssVar": "--sidebar",
        "description": "shadcn --sidebar. Surface that sits on the page background.",
        "light": {
          "hex": "#f5f5f5",
          "ref": "background/muted"
        },
        "dark": {
          "hex": "#292929",
          "ref": "background/muted"
        }
      },
      {
        "figma": "surface/sidebar-accent",
        "cssVar": "--sidebar-accent",
        "description": "shadcn --sidebar-accent. Surface that sits on the page background.",
        "light": {
          "hex": "#ebebeb",
          "ref": "background/accent"
        },
        "dark": {
          "hex": "#4d4d4d",
          "ref": "background/accent"
        }
      },
      {
        "figma": "surface/sidebar-primary",
        "cssVar": "--sidebar-primary",
        "description": "shadcn --sidebar-primary. Surface that sits on the page background.",
        "light": {
          "hex": "#0d4cfd",
          "ref": "primary/default"
        },
        "dark": {
          "hex": "#0d4cfd",
          "ref": "primary/default"
        }
      }
    ]
  },
  {
    "title": "Border",
    "tokens": [
      {
        "figma": "border/action",
        "cssVar": "--border-action",
        "description": "Border for selected or active controls.",
        "light": {
          "hex": "#0c3bca",
          "ref": "colors/blue/40"
        },
        "dark": {
          "hex": "#367dff",
          "ref": "colors/blue/60"
        }
      },
      {
        "figma": "border/action-hover",
        "cssVar": "--border-action-hover",
        "description": "Hover border for active controls.",
        "light": {
          "hex": "#0d4cfd",
          "ref": "colors/blue/50"
        },
        "dark": {
          "hex": "#0d4cfd",
          "ref": "colors/blue/50"
        }
      },
      {
        "figma": "border/alpha/4",
        "cssVar": "--border-alpha-4",
        "description": "Translucent border at 4% for use over imagery.",
        "light": {
          "hex": "#0000000a",
          "ref": "colors/neutral/black-alpha/4"
        },
        "dark": {
          "hex": "#ffffff0a",
          "ref": "colors/neutral/white-alpha/4"
        }
      },
      {
        "figma": "border/alpha/8",
        "cssVar": "--border-alpha-8",
        "description": "Translucent border at 8% for use over imagery.",
        "light": {
          "hex": "#00000014",
          "ref": "colors/neutral/black-alpha/8"
        },
        "dark": {
          "hex": "#ffffff14",
          "ref": "colors/neutral/white-alpha/8"
        }
      },
      {
        "figma": "border/alpha/16",
        "cssVar": "--border-alpha-16",
        "description": "Translucent border at 16% for use over imagery.",
        "light": {
          "hex": "#00000029",
          "ref": "colors/neutral/black-alpha/16"
        },
        "dark": {
          "hex": "#ffffff29",
          "ref": "colors/neutral/white-alpha/16"
        }
      },
      {
        "figma": "border/alpha/24",
        "cssVar": "--border-alpha-24",
        "description": "Translucent border at 24% for use over imagery.",
        "light": {
          "hex": "#0000003d",
          "ref": "colors/neutral/black-alpha/24"
        },
        "dark": {
          "hex": "#ffffff3d",
          "ref": "colors/neutral/white-alpha/24"
        }
      },
      {
        "figma": "border/default",
        "cssVar": "--border",
        "description": "shadcn --border. Default borders and dividers.",
        "light": {
          "hex": "#ebebeb",
          "ref": "colors/neutral/80"
        },
        "dark": {
          "hex": "#4d4d4d",
          "ref": "colors/neutral/30"
        }
      },
      {
        "figma": "border/focus",
        "cssVar": "--ring",
        "description": "shadcn --ring. Focus ring.",
        "light": {
          "hex": "#0d4cfd",
          "ref": "colors/blue/50"
        },
        "dark": {
          "hex": "#367dff",
          "ref": "colors/blue/60"
        }
      },
      {
        "figma": "border/input",
        "cssVar": "--input",
        "description": "shadcn --input. Form control borders.",
        "light": {
          "hex": "#cccccc",
          "ref": "colors/neutral/70"
        },
        "dark": {
          "hex": "#737373",
          "ref": "colors/neutral/40"
        }
      },
      {
        "figma": "border/sidebar",
        "cssVar": "--sidebar-border",
        "description": "shadcn --sidebar-border. ",
        "light": {
          "hex": "#ebebeb",
          "ref": "border/default"
        },
        "dark": {
          "hex": "#4d4d4d",
          "ref": "border/default"
        }
      },
      {
        "figma": "border/sidebar-focus",
        "cssVar": "--sidebar-ring",
        "description": "shadcn --sidebar-ring. ",
        "light": {
          "hex": "#0d4cfd",
          "ref": "border/focus"
        },
        "dark": {
          "hex": "#367dff",
          "ref": "border/focus"
        }
      },
      {
        "figma": "border/strong",
        "cssVar": "--border-strong",
        "description": "High-contrast border.",
        "light": {
          "hex": "#b2b2b2",
          "ref": "colors/neutral/60"
        },
        "dark": {
          "hex": "#8c8c8c",
          "ref": "colors/neutral/50"
        }
      }
    ]
  },
  {
    "title": "Primary",
    "tokens": [
      {
        "figma": "primary/default",
        "cssVar": "--primary",
        "description": "shadcn --primary. Brand actions (primary buttons, selection, links on emphasis).",
        "light": {
          "hex": "#0d4cfd",
          "ref": "colors/blue/50"
        },
        "dark": {
          "hex": "#0d4cfd",
          "ref": "colors/blue/50"
        }
      },
      {
        "figma": "primary/foreground",
        "cssVar": "--primary-foreground",
        "description": "shadcn --primary-foreground. Text on primary.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        }
      },
      {
        "figma": "primary/hover",
        "cssVar": "--button-primary-hover",
        "description": "primary button fill on hover.",
        "light": {
          "hex": "#0c3bca",
          "ref": "colors/blue/40"
        },
        "dark": {
          "hex": "#367dff",
          "ref": "colors/blue/60"
        }
      }
    ]
  },
  {
    "title": "Secondary",
    "tokens": [
      {
        "figma": "secondary/default",
        "cssVar": "--secondary",
        "description": "shadcn --secondary. Secondary button fill.",
        "light": {
          "hex": "#f5f5f5",
          "ref": "background/muted"
        },
        "dark": {
          "hex": "#292929",
          "ref": "background/muted"
        }
      },
      {
        "figma": "secondary/foreground",
        "cssVar": "--secondary-foreground",
        "description": "shadcn --secondary-foreground. secondary button label and icon.",
        "light": {
          "hex": "#1a1a1a",
          "ref": "foreground/default"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "foreground/default"
        }
      }
    ]
  },
  {
    "title": "Destructive",
    "tokens": [
      {
        "figma": "destructive/default",
        "cssVar": "--destructive",
        "description": "shadcn --destructive. Destructive actions and errors.",
        "light": {
          "hex": "#d41616",
          "ref": "colors/red/50"
        },
        "dark": {
          "hex": "#d41616",
          "ref": "colors/red/50"
        }
      },
      {
        "figma": "destructive/foreground",
        "cssVar": "--destructive-foreground",
        "description": "shadcn --destructive-foreground. Text on destructive.",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "destructive/hover",
        "cssVar": "--button-destructive-hover",
        "description": "destructive button fill on hover.",
        "light": {
          "hex": "#af1111",
          "ref": "colors/red/40"
        },
        "dark": {
          "hex": "#e24444",
          "ref": "colors/red/60"
        }
      }
    ]
  },
  {
    "title": "Button",
    "tokens": [
      {
        "figma": "button/neutral/default",
        "cssVar": "--button-neutral",
        "description": "neutral button fill.",
        "light": {
          "hex": "#0d0d0d",
          "ref": "colors/neutral/black"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        }
      },
      {
        "figma": "button/neutral/foreground",
        "cssVar": "--button-neutral-foreground",
        "description": "neutral button label and icon.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#0d0d0d",
          "ref": "colors/neutral/black"
        }
      },
      {
        "figma": "button/neutral/hover",
        "cssVar": "--button-neutral-hover",
        "description": "neutral button fill on hover.",
        "light": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        },
        "dark": {
          "hex": "#ebebeb",
          "ref": "colors/neutral/80"
        }
      },
      {
        "figma": "button/outline/default",
        "cssVar": "--button-outline",
        "description": "outline button fill.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        }
      },
      {
        "figma": "button/outline/foreground",
        "cssVar": "--button-outline-foreground",
        "description": "outline button label and icon.",
        "light": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        }
      },
      {
        "figma": "button/outline/hover",
        "cssVar": "--button-outline-hover",
        "description": "outline button fill on hover.",
        "light": {
          "hex": "#f5f5f5",
          "ref": "colors/neutral/90"
        },
        "dark": {
          "hex": "#292929",
          "ref": "colors/neutral/20"
        }
      }
    ]
  },
  {
    "title": "Status · info",
    "tokens": [
      {
        "figma": "status/info/default",
        "cssVar": "--info",
        "description": "Extension status family: informational / brand action: base tone (fills, icons).",
        "light": {
          "hex": "#0d4cfd",
          "ref": "primary/default"
        },
        "dark": {
          "hex": "#0d4cfd",
          "ref": "primary/default"
        }
      },
      {
        "figma": "status/info/foreground",
        "cssVar": "--info-foreground",
        "description": "Extension status family: informational / brand action: text on the default tone.",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "status/info/medium",
        "cssVar": "--info-medium",
        "description": "Extension status family: informational / brand action: medium tone.",
        "light": {
          "hex": "#092d90",
          "ref": "colors/blue/30"
        },
        "dark": {
          "hex": "#b4defd",
          "ref": "colors/blue/80"
        }
      },
      {
        "figma": "status/info/muted",
        "cssVar": "--info-muted",
        "description": "Extension status family: informational / brand action: muted tint.",
        "light": {
          "hex": "#b4defd",
          "ref": "colors/blue/80"
        },
        "dark": {
          "hex": "#092d90",
          "ref": "colors/blue/30"
        }
      },
      {
        "figma": "status/info/soft",
        "cssVar": "--info-soft",
        "description": "Extension status family: informational / brand action: soft tone, borders on subtle backgrounds.",
        "light": {
          "hex": "#d3edfd",
          "ref": "colors/blue/90"
        },
        "dark": {
          "hex": "#0c2664",
          "ref": "colors/blue/20"
        }
      },
      {
        "figma": "status/info/strong",
        "cssVar": "--info-strong",
        "description": "Extension status family: informational / brand action: strongest tone, text on subtle backgrounds.",
        "light": {
          "hex": "#081436",
          "ref": "colors/blue/10"
        },
        "dark": {
          "hex": "#d3edfd",
          "ref": "colors/blue/90"
        }
      },
      {
        "figma": "status/info/subtle",
        "cssVar": "--info-subtle",
        "description": "Extension status family: informational / brand action: subtle background tint.",
        "light": {
          "hex": "#e6f4fe",
          "ref": "colors/blue/100"
        },
        "dark": {
          "hex": "#081436",
          "ref": "colors/blue/10"
        }
      }
    ]
  },
  {
    "title": "Status · success",
    "tokens": [
      {
        "figma": "status/success/default",
        "cssVar": "--success",
        "description": "Extension status family: success: base tone (fills, icons).",
        "light": {
          "hex": "#0c8d40",
          "ref": "colors/green/50"
        },
        "dark": {
          "hex": "#0c8d40",
          "ref": "colors/green/50"
        }
      },
      {
        "figma": "status/success/foreground",
        "cssVar": "--success-foreground",
        "description": "Extension status family: success: text on the default tone.",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "status/success/medium",
        "cssVar": "--success-medium",
        "description": "Extension status family: success: medium tone.",
        "light": {
          "hex": "#075526",
          "ref": "colors/green/30"
        },
        "dark": {
          "hex": "#9ed1b3",
          "ref": "colors/green/80"
        }
      },
      {
        "figma": "status/success/muted",
        "cssVar": "--success-muted",
        "description": "Extension status family: success: muted tint.",
        "light": {
          "hex": "#9ed1b3",
          "ref": "colors/green/80"
        },
        "dark": {
          "hex": "#075526",
          "ref": "colors/green/30"
        }
      },
      {
        "figma": "status/success/soft",
        "cssVar": "--success-soft",
        "description": "Extension status family: success: soft tone, borders on subtle backgrounds.",
        "light": {
          "hex": "#c9edd8",
          "ref": "colors/green/90"
        },
        "dark": {
          "hex": "#05381a",
          "ref": "colors/green/20"
        }
      },
      {
        "figma": "status/success/strong",
        "cssVar": "--success-strong",
        "description": "Extension status family: success: strongest tone, text on subtle backgrounds.",
        "light": {
          "hex": "#021c0d",
          "ref": "colors/green/10"
        },
        "dark": {
          "hex": "#c9edd8",
          "ref": "colors/green/90"
        }
      },
      {
        "figma": "status/success/subtle",
        "cssVar": "--success-subtle",
        "description": "Extension status family: success: subtle background tint.",
        "light": {
          "hex": "#e6f9ee",
          "ref": "colors/green/100"
        },
        "dark": {
          "hex": "#021c0d",
          "ref": "colors/green/10"
        }
      }
    ]
  },
  {
    "title": "Status · warning",
    "tokens": [
      {
        "figma": "status/warning/default",
        "cssVar": "--warning",
        "description": "Extension status family: warning: base tone (fills, icons).",
        "light": {
          "hex": "#ed8b0b",
          "ref": "colors/yellow/50"
        },
        "dark": {
          "hex": "#ed8b0b",
          "ref": "colors/yellow/50"
        }
      },
      {
        "figma": "status/warning/foreground",
        "cssVar": "--warning-foreground",
        "description": "Extension status family: warning: text on the default tone. Dark text in both modes for contrast on amber.",
        "light": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        }
      },
      {
        "figma": "status/warning/medium",
        "cssVar": "--warning-medium",
        "description": "Extension status family: warning: medium tone.",
        "light": {
          "hex": "#8e3f07",
          "ref": "colors/yellow/30"
        },
        "dark": {
          "hex": "#f9de9a",
          "ref": "colors/yellow/80"
        }
      },
      {
        "figma": "status/warning/muted",
        "cssVar": "--warning-muted",
        "description": "Extension status family: warning: muted tint.",
        "light": {
          "hex": "#f9de9a",
          "ref": "colors/yellow/80"
        },
        "dark": {
          "hex": "#8e3f07",
          "ref": "colors/yellow/30"
        }
      },
      {
        "figma": "status/warning/soft",
        "cssVar": "--warning-soft",
        "description": "Extension status family: warning: soft tone, borders on subtle backgrounds.",
        "light": {
          "hex": "#fdeec4",
          "ref": "colors/yellow/90"
        },
        "dark": {
          "hex": "#5f2804",
          "ref": "colors/yellow/20"
        }
      },
      {
        "figma": "status/warning/strong",
        "cssVar": "--warning-strong",
        "description": "Extension status family: warning: strongest tone, text on subtle backgrounds.",
        "light": {
          "hex": "#2f1902",
          "ref": "colors/yellow/10"
        },
        "dark": {
          "hex": "#fdeec4",
          "ref": "colors/yellow/90"
        }
      },
      {
        "figma": "status/warning/subtle",
        "cssVar": "--warning-subtle",
        "description": "Extension status family: warning: subtle background tint.",
        "light": {
          "hex": "#fef5dd",
          "ref": "colors/yellow/100"
        },
        "dark": {
          "hex": "#2f1902",
          "ref": "colors/yellow/10"
        }
      }
    ]
  },
  {
    "title": "Status · danger",
    "tokens": [
      {
        "figma": "status/danger/default",
        "cssVar": "--danger",
        "description": "Extension status family: error / critical: base tone (fills, icons).",
        "light": {
          "hex": "#d41616",
          "ref": "destructive/default"
        },
        "dark": {
          "hex": "#d41616",
          "ref": "destructive/default"
        }
      },
      {
        "figma": "status/danger/foreground",
        "cssVar": "--danger-foreground",
        "description": "Extension status family: error / critical: text on the default tone.",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "status/danger/medium",
        "cssVar": "--danger-medium",
        "description": "Extension status family: error / critical: medium tone.",
        "light": {
          "hex": "#830d0d",
          "ref": "colors/red/30"
        },
        "dark": {
          "hex": "#f2abab",
          "ref": "colors/red/80"
        }
      },
      {
        "figma": "status/danger/muted",
        "cssVar": "--danger-muted",
        "description": "Extension status family: error / critical: muted tint.",
        "light": {
          "hex": "#f2abab",
          "ref": "colors/red/80"
        },
        "dark": {
          "hex": "#830d0d",
          "ref": "colors/red/30"
        }
      },
      {
        "figma": "status/danger/soft",
        "cssVar": "--danger-soft",
        "description": "Extension status family: error / critical: soft tone, borders on subtle backgrounds.",
        "light": {
          "hex": "#f9dcdc",
          "ref": "colors/red/90"
        },
        "dark": {
          "hex": "#580808",
          "ref": "colors/red/20"
        }
      },
      {
        "figma": "status/danger/strong",
        "cssVar": "--danger-strong",
        "description": "Extension status family: error / critical: strongest tone, text on subtle backgrounds.",
        "light": {
          "hex": "#2c0404",
          "ref": "colors/red/10"
        },
        "dark": {
          "hex": "#f9dcdc",
          "ref": "colors/red/90"
        }
      },
      {
        "figma": "status/danger/subtle",
        "cssVar": "--danger-subtle",
        "description": "Extension status family: error / critical: subtle background tint.",
        "light": {
          "hex": "#fde8e8",
          "ref": "colors/red/100"
        },
        "dark": {
          "hex": "#2c0404",
          "ref": "colors/red/10"
        }
      }
    ]
  },
  {
    "title": "Agent",
    "tokens": [
      {
        "figma": "agent/default",
        "cssVar": "--agent",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): base tone (fills, icons).",
        "light": {
          "hex": "#5d2de6",
          "ref": "colors/purple/50"
        },
        "dark": {
          "hex": "#5d2de6",
          "ref": "colors/purple/50"
        }
      },
      {
        "figma": "agent/foreground",
        "cssVar": "--agent-foreground",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): text on the default tone.",
        "light": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        },
        "dark": {
          "hex": "#ffffff",
          "ref": "primary/foreground"
        }
      },
      {
        "figma": "agent/medium",
        "cssVar": "--agent-medium",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): medium tone.",
        "light": {
          "hex": "#381b8a",
          "ref": "colors/purple/30"
        },
        "dark": {
          "hex": "#beabf5",
          "ref": "colors/purple/80"
        }
      },
      {
        "figma": "agent/muted",
        "cssVar": "--agent-muted",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): muted tint.",
        "light": {
          "hex": "#beabf5",
          "ref": "colors/purple/80"
        },
        "dark": {
          "hex": "#381b8a",
          "ref": "colors/purple/30"
        }
      },
      {
        "figma": "agent/soft",
        "cssVar": "--agent-soft",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): soft tone, borders on subtle backgrounds.",
        "light": {
          "hex": "#dfd5fa",
          "ref": "colors/purple/90"
        },
        "dark": {
          "hex": "#25125c",
          "ref": "colors/purple/20"
        }
      },
      {
        "figma": "agent/strong",
        "cssVar": "--agent-strong",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): strongest tone, text on subtle backgrounds.",
        "light": {
          "hex": "#13092e",
          "ref": "colors/purple/10"
        },
        "dark": {
          "hex": "#dfd5fa",
          "ref": "colors/purple/90"
        }
      },
      {
        "figma": "agent/subtle",
        "cssVar": "--agent-subtle",
        "description": "Extension status family: AI agent states (thinking, streaming, tools, citations): subtle background tint.",
        "light": {
          "hex": "#efeafd",
          "ref": "colors/purple/100"
        },
        "dark": {
          "hex": "#13092e",
          "ref": "colors/purple/10"
        }
      }
    ]
  },
  {
    "title": "Chart",
    "tokens": [
      {
        "figma": "chart/1",
        "cssVar": "--chart-1",
        "description": "shadcn --chart-1. Data visualisation series 1.",
        "light": {
          "hex": "#0d4cfd",
          "ref": "status/info/default"
        },
        "dark": {
          "hex": "#0d4cfd",
          "ref": "status/info/default"
        }
      },
      {
        "figma": "chart/2",
        "cssVar": "--chart-2",
        "description": "shadcn --chart-2. Data visualisation series 2.",
        "light": {
          "hex": "#5d2de6",
          "ref": "agent/default"
        },
        "dark": {
          "hex": "#5d2de6",
          "ref": "agent/default"
        }
      },
      {
        "figma": "chart/3",
        "cssVar": "--chart-3",
        "description": "shadcn --chart-3. Data visualisation series 3.",
        "light": {
          "hex": "#0c8d40",
          "ref": "status/success/default"
        },
        "dark": {
          "hex": "#0c8d40",
          "ref": "status/success/default"
        }
      },
      {
        "figma": "chart/4",
        "cssVar": "--chart-4",
        "description": "shadcn --chart-4. Data visualisation series 4.",
        "light": {
          "hex": "#ed8b0b",
          "ref": "status/warning/default"
        },
        "dark": {
          "hex": "#ed8b0b",
          "ref": "status/warning/default"
        }
      },
      {
        "figma": "chart/5",
        "cssVar": "--chart-5",
        "description": "shadcn --chart-5. Data visualisation series 5.",
        "light": {
          "hex": "#d41616",
          "ref": "status/danger/default"
        },
        "dark": {
          "hex": "#d41616",
          "ref": "status/danger/default"
        }
      }
    ]
  },
  {
    "title": "Overlay",
    "tokens": [
      {
        "figma": "overlay/dim/0",
        "cssVar": "--overlay-0",
        "description": "Overlay (darkens in light mode, lightens in dark) at 0% for scrims and hover washes.",
        "light": {
          "hex": "#00000000",
          "ref": "colors/neutral/black-alpha/0"
        },
        "dark": {
          "hex": "#ffffff00",
          "ref": "colors/neutral/white-alpha/0"
        }
      },
      {
        "figma": "overlay/dim/4",
        "cssVar": "--overlay-4",
        "description": "Overlay (darkens in light mode, lightens in dark) at 4% for scrims and hover washes.",
        "light": {
          "hex": "#0000000a",
          "ref": "colors/neutral/black-alpha/4"
        },
        "dark": {
          "hex": "#ffffff0a",
          "ref": "colors/neutral/white-alpha/4"
        }
      },
      {
        "figma": "overlay/dim/8",
        "cssVar": "--overlay-8",
        "description": "Overlay (darkens in light mode, lightens in dark) at 8% for scrims and hover washes.",
        "light": {
          "hex": "#00000014",
          "ref": "colors/neutral/black-alpha/8"
        },
        "dark": {
          "hex": "#ffffff14",
          "ref": "colors/neutral/white-alpha/8"
        }
      },
      {
        "figma": "overlay/dim/16",
        "cssVar": "--overlay-16",
        "description": "Overlay (darkens in light mode, lightens in dark) at 16% for scrims and hover washes.",
        "light": {
          "hex": "#00000029",
          "ref": "colors/neutral/black-alpha/16"
        },
        "dark": {
          "hex": "#ffffff29",
          "ref": "colors/neutral/white-alpha/16"
        }
      },
      {
        "figma": "overlay/dim/24",
        "cssVar": "--overlay-24",
        "description": "Overlay (darkens in light mode, lightens in dark) at 24% for scrims and hover washes.",
        "light": {
          "hex": "#0000003d",
          "ref": "colors/neutral/black-alpha/24"
        },
        "dark": {
          "hex": "#ffffff3d",
          "ref": "colors/neutral/white-alpha/24"
        }
      },
      {
        "figma": "overlay/dim/32",
        "cssVar": "--overlay-32",
        "description": "Overlay (darkens in light mode, lightens in dark) at 32% for scrims and hover washes.",
        "light": {
          "hex": "#00000052",
          "ref": "colors/neutral/black-alpha/32"
        },
        "dark": {
          "hex": "#ffffff52",
          "ref": "colors/neutral/white-alpha/32"
        }
      },
      {
        "figma": "overlay/dim/64",
        "cssVar": "--overlay-64",
        "description": "Overlay (darkens in light mode, lightens in dark) at 64% for scrims and hover washes.",
        "light": {
          "hex": "#000000a3",
          "ref": "colors/neutral/black-alpha/64"
        },
        "dark": {
          "hex": "#ffffffa3",
          "ref": "colors/neutral/white-alpha/64"
        }
      },
      {
        "figma": "overlay/inverse/0",
        "cssVar": "--overlay-inverse-0",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 0% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff00",
          "ref": "colors/neutral/white-alpha/0"
        },
        "dark": {
          "hex": "#00000000",
          "ref": "colors/neutral/black-alpha/0"
        }
      },
      {
        "figma": "overlay/inverse/4",
        "cssVar": "--overlay-inverse-4",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 4% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff0a",
          "ref": "colors/neutral/white-alpha/4"
        },
        "dark": {
          "hex": "#0000000a",
          "ref": "colors/neutral/black-alpha/4"
        }
      },
      {
        "figma": "overlay/inverse/8",
        "cssVar": "--overlay-inverse-8",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 8% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff14",
          "ref": "colors/neutral/white-alpha/8"
        },
        "dark": {
          "hex": "#00000014",
          "ref": "colors/neutral/black-alpha/8"
        }
      },
      {
        "figma": "overlay/inverse/16",
        "cssVar": "--overlay-inverse-16",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 16% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff29",
          "ref": "colors/neutral/white-alpha/16"
        },
        "dark": {
          "hex": "#00000029",
          "ref": "colors/neutral/black-alpha/16"
        }
      },
      {
        "figma": "overlay/inverse/24",
        "cssVar": "--overlay-inverse-24",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 24% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff3d",
          "ref": "colors/neutral/white-alpha/24"
        },
        "dark": {
          "hex": "#0000003d",
          "ref": "colors/neutral/black-alpha/24"
        }
      },
      {
        "figma": "overlay/inverse/32",
        "cssVar": "--overlay-inverse-32",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 32% for scrims and hover washes.",
        "light": {
          "hex": "#ffffff52",
          "ref": "colors/neutral/white-alpha/32"
        },
        "dark": {
          "hex": "#00000052",
          "ref": "colors/neutral/black-alpha/32"
        }
      },
      {
        "figma": "overlay/inverse/64",
        "cssVar": "--overlay-inverse-64",
        "description": "Inverse overlay (lightens in light mode, darkens in dark) at 64% for scrims and hover washes.",
        "light": {
          "hex": "#ffffffa3",
          "ref": "colors/neutral/white-alpha/64"
        },
        "dark": {
          "hex": "#000000a3",
          "ref": "colors/neutral/black-alpha/64"
        }
      },
      {
        "figma": "overlay/scrim",
        "cssVar": "--overlay",
        "description": "",
        "light": {
          "hex": "#0000007a",
          "ref": "colors/neutral/black-alpha/48"
        },
        "dark": {
          "hex": "#000000b8",
          "ref": "colors/neutral/black-alpha/72"
        }
      }
    ]
  },
  {
    "title": "Gradient",
    "tokens": [
      {
        "figma": "gradient/neutral/end",
        "cssVar": "--gradient-neutral-end",
        "description": "Gradient stop.",
        "light": {
          "hex": "#ffffff00",
          "ref": "colors/neutral/white-alpha/0"
        },
        "dark": {
          "hex": "#00000000",
          "ref": "colors/neutral/black-alpha/0"
        }
      },
      {
        "figma": "gradient/neutral/start",
        "cssVar": "--gradient-neutral-start",
        "description": "Gradient stop.",
        "light": {
          "hex": "#ffffff",
          "ref": "colors/neutral/white"
        },
        "dark": {
          "hex": "#1a1a1a",
          "ref": "colors/neutral/10"
        }
      }
    ]
  },
  {
    "title": "Shadow colors",
    "tokens": [
      {
        "figma": "shadow/medium",
        "cssVar": "--shadow-color-medium",
        "description": "",
        "light": {
          "hex": "#00000029",
          "ref": "colors/neutral/black-alpha/16"
        },
        "dark": {
          "hex": "#0000007a",
          "ref": "colors/neutral/black-alpha/48"
        }
      },
      {
        "figma": "shadow/soft",
        "cssVar": "--shadow-color-soft",
        "description": "",
        "light": {
          "hex": "#00000014",
          "ref": "colors/neutral/black-alpha/8"
        },
        "dark": {
          "hex": "#0000003d",
          "ref": "colors/neutral/black-alpha/24"
        }
      },
      {
        "figma": "shadow/strong",
        "cssVar": "--shadow-color-strong",
        "description": "",
        "light": {
          "hex": "#0000003d",
          "ref": "colors/neutral/black-alpha/24"
        },
        "dark": {
          "hex": "#000000a3",
          "ref": "colors/neutral/black-alpha/64"
        }
      }
    ]
  }
] as const

export const contrastPairs = [
  {
    "fg": "--agent-foreground",
    "bg": "--agent",
    "kind": "text",
    "light": 7.04,
    "dark": 7.04
  },
  {
    "fg": "--agent-strong",
    "bg": "--agent-subtle",
    "kind": "text",
    "light": 16.14,
    "dark": 13.59
  },
  {
    "fg": "--button-neutral-foreground",
    "bg": "--button-neutral",
    "kind": "text",
    "light": 19.44,
    "dark": 19.44
  },
  {
    "fg": "--button-outline-foreground",
    "bg": "--button-outline",
    "kind": "text",
    "light": 17.4,
    "dark": 17.4
  },
  {
    "fg": "--destructive-foreground",
    "bg": "--destructive",
    "kind": "text",
    "light": 5.35,
    "dark": 5.35
  },
  {
    "fg": "--muted-foreground",
    "bg": "--muted",
    "kind": "text",
    "light": 7.75,
    "dark": 6.86
  },
  {
    "fg": "--accent-foreground",
    "bg": "--accent",
    "kind": "text",
    "light": 14.6,
    "dark": 8.45
  },
  {
    "fg": "--card-foreground",
    "bg": "--card",
    "kind": "text",
    "light": 17.4,
    "dark": 17.4
  },
  {
    "fg": "--popover-foreground",
    "bg": "--popover",
    "kind": "text",
    "light": 17.4,
    "dark": 17.4
  },
  {
    "fg": "--sidebar-foreground",
    "bg": "--sidebar",
    "kind": "text",
    "light": 15.96,
    "dark": 14.55
  },
  {
    "fg": "--sidebar-accent-foreground",
    "bg": "--sidebar-accent",
    "kind": "text",
    "light": 14.6,
    "dark": 8.45
  },
  {
    "fg": "--sidebar-primary-foreground",
    "bg": "--sidebar-primary",
    "kind": "text",
    "light": 6.05,
    "dark": 6.05
  },
  {
    "fg": "--primary-foreground",
    "bg": "--primary",
    "kind": "text",
    "light": 6.05,
    "dark": 6.05
  },
  {
    "fg": "--secondary-foreground",
    "bg": "--secondary",
    "kind": "text",
    "light": 15.96,
    "dark": 14.55
  },
  {
    "fg": "--danger-foreground",
    "bg": "--danger",
    "kind": "text",
    "light": 5.35,
    "dark": 5.35
  },
  {
    "fg": "--danger-strong",
    "bg": "--danger-subtle",
    "kind": "text",
    "light": 15.88,
    "dark": 14.47
  },
  {
    "fg": "--info-foreground",
    "bg": "--info",
    "kind": "text",
    "light": 6.05,
    "dark": 6.05
  },
  {
    "fg": "--info-strong",
    "bg": "--info-subtle",
    "kind": "text",
    "light": 16.1,
    "dark": 14.87
  },
  {
    "fg": "--success-foreground",
    "bg": "--success",
    "kind": "text",
    "light": 4.29,
    "dark": 4.29
  },
  {
    "fg": "--success-strong",
    "bg": "--success-subtle",
    "kind": "text",
    "light": 16.3,
    "dark": 14.12
  },
  {
    "fg": "--warning-foreground",
    "bg": "--warning",
    "kind": "text",
    "light": 6.88,
    "dark": 6.88
  },
  {
    "fg": "--warning-strong",
    "bg": "--warning-subtle",
    "kind": "text",
    "light": 15.32,
    "dark": 14.44
  },
  {
    "fg": "--foreground",
    "bg": "--background",
    "kind": "text",
    "light": 17.4,
    "dark": 17.4
  },
  {
    "fg": "--muted-foreground",
    "bg": "--background",
    "kind": "text",
    "light": 8.45,
    "dark": 8.21
  },
  {
    "fg": "--foreground-subtle",
    "bg": "--background",
    "kind": "text",
    "light": 4.74,
    "dark": 5.18
  },
  {
    "fg": "--foreground-link",
    "bg": "--background",
    "kind": "text",
    "light": 8.42,
    "dark": 4.59
  },
  {
    "fg": "--foreground-inverse",
    "bg": "--background-inverse",
    "kind": "text",
    "light": 19.44,
    "dark": 17.4
  },
  {
    "fg": "--foreground-disabled",
    "bg": "--background",
    "kind": "disabled",
    "light": 3.36,
    "dark": 2.06
  },
  {
    "fg": "--ring",
    "bg": "--background",
    "kind": "non-text",
    "light": 6.05,
    "dark": 4.59
  }
] as const

export const primitivePalettes = [
  {
    "family": "blue",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--blue-10",
        "hex": "#081436"
      },
      {
        "name": "20",
        "cssVar": "--blue-20",
        "hex": "#0c2664"
      },
      {
        "name": "30",
        "cssVar": "--blue-30",
        "hex": "#092d90"
      },
      {
        "name": "40",
        "cssVar": "--blue-40",
        "hex": "#0c3bca"
      },
      {
        "name": "50",
        "cssVar": "--blue-50",
        "hex": "#0d4cfd"
      },
      {
        "name": "60",
        "cssVar": "--blue-60",
        "hex": "#367dff"
      },
      {
        "name": "70",
        "cssVar": "--blue-70",
        "hex": "#5ca3ff"
      },
      {
        "name": "80",
        "cssVar": "--blue-80",
        "hex": "#b4defd"
      },
      {
        "name": "90",
        "cssVar": "--blue-90",
        "hex": "#d3edfd"
      },
      {
        "name": "100",
        "cssVar": "--blue-100",
        "hex": "#e6f4fe"
      }
    ]
  },
  {
    "family": "green",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--green-10",
        "hex": "#021c0d"
      },
      {
        "name": "20",
        "cssVar": "--green-20",
        "hex": "#05381a"
      },
      {
        "name": "30",
        "cssVar": "--green-30",
        "hex": "#075526"
      },
      {
        "name": "40",
        "cssVar": "--green-40",
        "hex": "#0a7133"
      },
      {
        "name": "50",
        "cssVar": "--green-50",
        "hex": "#0c8d40"
      },
      {
        "name": "60",
        "cssVar": "--green-60",
        "hex": "#3da466"
      },
      {
        "name": "70",
        "cssVar": "--green-70",
        "hex": "#6dbb8c"
      },
      {
        "name": "80",
        "cssVar": "--green-80",
        "hex": "#9ed1b3"
      },
      {
        "name": "90",
        "cssVar": "--green-90",
        "hex": "#c9edd8"
      },
      {
        "name": "100",
        "cssVar": "--green-100",
        "hex": "#e6f9ee"
      }
    ]
  },
  {
    "family": "neutral",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--neutral-10",
        "hex": "#1a1a1a"
      },
      {
        "name": "20",
        "cssVar": "--neutral-20",
        "hex": "#292929"
      },
      {
        "name": "30",
        "cssVar": "--neutral-30",
        "hex": "#4d4d4d"
      },
      {
        "name": "40",
        "cssVar": "--neutral-40",
        "hex": "#737373"
      },
      {
        "name": "50",
        "cssVar": "--neutral-50",
        "hex": "#8c8c8c"
      },
      {
        "name": "60",
        "cssVar": "--neutral-60",
        "hex": "#b2b2b2"
      },
      {
        "name": "70",
        "cssVar": "--neutral-70",
        "hex": "#cccccc"
      },
      {
        "name": "80",
        "cssVar": "--neutral-80",
        "hex": "#ebebeb"
      },
      {
        "name": "90",
        "cssVar": "--neutral-90",
        "hex": "#f5f5f5"
      },
      {
        "name": "black",
        "cssVar": "--neutral-black",
        "hex": "#0d0d0d"
      },
      {
        "name": "black-alpha/0",
        "cssVar": "--neutral-black-alpha-0",
        "hex": "#00000000"
      },
      {
        "name": "black-alpha/4",
        "cssVar": "--neutral-black-alpha-4",
        "hex": "#0000000a"
      },
      {
        "name": "black-alpha/8",
        "cssVar": "--neutral-black-alpha-8",
        "hex": "#00000014"
      },
      {
        "name": "black-alpha/16",
        "cssVar": "--neutral-black-alpha-16",
        "hex": "#00000029"
      },
      {
        "name": "black-alpha/24",
        "cssVar": "--neutral-black-alpha-24",
        "hex": "#0000003d"
      },
      {
        "name": "black-alpha/32",
        "cssVar": "--neutral-black-alpha-32",
        "hex": "#00000052"
      },
      {
        "name": "black-alpha/48",
        "cssVar": "--neutral-black-alpha-48",
        "hex": "#0000007a"
      },
      {
        "name": "black-alpha/64",
        "cssVar": "--neutral-black-alpha-64",
        "hex": "#000000a3"
      },
      {
        "name": "black-alpha/72",
        "cssVar": "--neutral-black-alpha-72",
        "hex": "#000000b8"
      },
      {
        "name": "black-alpha/88",
        "cssVar": "--neutral-black-alpha-88",
        "hex": "#000000e0"
      },
      {
        "name": "white",
        "cssVar": "--neutral-white",
        "hex": "#ffffff"
      },
      {
        "name": "white-alpha/0",
        "cssVar": "--neutral-white-alpha-0",
        "hex": "#ffffff00"
      },
      {
        "name": "white-alpha/4",
        "cssVar": "--neutral-white-alpha-4",
        "hex": "#ffffff0a"
      },
      {
        "name": "white-alpha/8",
        "cssVar": "--neutral-white-alpha-8",
        "hex": "#ffffff14"
      },
      {
        "name": "white-alpha/16",
        "cssVar": "--neutral-white-alpha-16",
        "hex": "#ffffff29"
      },
      {
        "name": "white-alpha/24",
        "cssVar": "--neutral-white-alpha-24",
        "hex": "#ffffff3d"
      },
      {
        "name": "white-alpha/32",
        "cssVar": "--neutral-white-alpha-32",
        "hex": "#ffffff52"
      },
      {
        "name": "white-alpha/48",
        "cssVar": "--neutral-white-alpha-48",
        "hex": "#ffffff7a"
      },
      {
        "name": "white-alpha/64",
        "cssVar": "--neutral-white-alpha-64",
        "hex": "#ffffffa3"
      },
      {
        "name": "white-alpha/72",
        "cssVar": "--neutral-white-alpha-72",
        "hex": "#ffffffb8"
      },
      {
        "name": "white-alpha/88",
        "cssVar": "--neutral-white-alpha-88",
        "hex": "#ffffffe0"
      }
    ]
  },
  {
    "family": "pink",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--pink-10",
        "hex": "#320c20"
      },
      {
        "name": "20",
        "cssVar": "--pink-20",
        "hex": "#641741"
      },
      {
        "name": "30",
        "cssVar": "--pink-30",
        "hex": "#972361"
      },
      {
        "name": "40",
        "cssVar": "--pink-40",
        "hex": "#c92e82"
      },
      {
        "name": "50",
        "cssVar": "--pink-50",
        "hex": "#fb3aa2"
      },
      {
        "name": "60",
        "cssVar": "--pink-60",
        "hex": "#fc61b5"
      },
      {
        "name": "70",
        "cssVar": "--pink-70",
        "hex": "#fd89c7"
      },
      {
        "name": "80",
        "cssVar": "--pink-80",
        "hex": "#fdb0da"
      },
      {
        "name": "90",
        "cssVar": "--pink-90",
        "hex": "#fed8ec"
      },
      {
        "name": "100",
        "cssVar": "--pink-100",
        "hex": "#ffebf6"
      }
    ]
  },
  {
    "family": "purple",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--purple-10",
        "hex": "#13092e"
      },
      {
        "name": "20",
        "cssVar": "--purple-20",
        "hex": "#25125c"
      },
      {
        "name": "30",
        "cssVar": "--purple-30",
        "hex": "#381b8a"
      },
      {
        "name": "40",
        "cssVar": "--purple-40",
        "hex": "#4a24b8"
      },
      {
        "name": "50",
        "cssVar": "--purple-50",
        "hex": "#5d2de6"
      },
      {
        "name": "60",
        "cssVar": "--purple-60",
        "hex": "#7241ff"
      },
      {
        "name": "70",
        "cssVar": "--purple-70",
        "hex": "#9e81f0"
      },
      {
        "name": "80",
        "cssVar": "--purple-80",
        "hex": "#beabf5"
      },
      {
        "name": "90",
        "cssVar": "--purple-90",
        "hex": "#dfd5fa"
      },
      {
        "name": "100",
        "cssVar": "--purple-100",
        "hex": "#efeafd"
      }
    ]
  },
  {
    "family": "red",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--red-10",
        "hex": "#2c0404"
      },
      {
        "name": "20",
        "cssVar": "--red-20",
        "hex": "#580808"
      },
      {
        "name": "30",
        "cssVar": "--red-30",
        "hex": "#830d0d"
      },
      {
        "name": "40",
        "cssVar": "--red-40",
        "hex": "#af1111"
      },
      {
        "name": "50",
        "cssVar": "--red-50",
        "hex": "#d41616"
      },
      {
        "name": "60",
        "cssVar": "--red-60",
        "hex": "#e24444"
      },
      {
        "name": "70",
        "cssVar": "--red-70",
        "hex": "#e97373"
      },
      {
        "name": "80",
        "cssVar": "--red-80",
        "hex": "#f2abab"
      },
      {
        "name": "90",
        "cssVar": "--red-90",
        "hex": "#f9dcdc"
      },
      {
        "name": "100",
        "cssVar": "--red-100",
        "hex": "#fde8e8"
      }
    ]
  },
  {
    "family": "yellow",
    "swatches": [
      {
        "name": "10",
        "cssVar": "--yellow-10",
        "hex": "#2f1902"
      },
      {
        "name": "20",
        "cssVar": "--yellow-20",
        "hex": "#5f2804"
      },
      {
        "name": "30",
        "cssVar": "--yellow-30",
        "hex": "#8e3f07"
      },
      {
        "name": "40",
        "cssVar": "--yellow-40",
        "hex": "#be6009"
      },
      {
        "name": "50",
        "cssVar": "--yellow-50",
        "hex": "#ed8b0b"
      },
      {
        "name": "60",
        "cssVar": "--yellow-60",
        "hex": "#f1a32f"
      },
      {
        "name": "70",
        "cssVar": "--yellow-70",
        "hex": "#f4c56d"
      },
      {
        "name": "80",
        "cssVar": "--yellow-80",
        "hex": "#f9de9a"
      },
      {
        "name": "90",
        "cssVar": "--yellow-90",
        "hex": "#fdeec4"
      },
      {
        "name": "100",
        "cssVar": "--yellow-100",
        "hex": "#fef5dd"
      }
    ]
  }
] as const

export const textStyles = [
  {
    "figma": "heading/6xl",
    "utility": "type-heading-6xl",
    "description": "font-heading text-6xl font-semibold tracking-tight · 56/56 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 56,
      "mobile": 48
    },
    "lineHeight": {
      "desktop": 56,
      "mobile": 48
    },
    "weight": 600,
    "tracking": {
      "desktop": -1,
      "mobile": -1
    },
    "underline": false
  },
  {
    "figma": "heading/5xl",
    "utility": "type-heading-5xl",
    "description": "font-heading text-5xl font-semibold tracking-tight · 48/48 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 48,
      "mobile": 40
    },
    "lineHeight": {
      "desktop": 48,
      "mobile": 40
    },
    "weight": 600,
    "tracking": {
      "desktop": -1,
      "mobile": -1
    },
    "underline": false
  },
  {
    "figma": "heading/4xl",
    "utility": "type-heading-4xl",
    "description": "font-heading text-4xl font-semibold tracking-tight · 40/44 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 40,
      "mobile": 36
    },
    "lineHeight": {
      "desktop": 44,
      "mobile": 40
    },
    "weight": 600,
    "tracking": {
      "desktop": -1,
      "mobile": -1
    },
    "underline": false
  },
  {
    "figma": "heading/3xl",
    "utility": "type-heading-3xl",
    "description": "font-heading text-3xl font-semibold tracking-tight · 32/40 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 32,
      "mobile": 28
    },
    "lineHeight": {
      "desktop": 40,
      "mobile": 36
    },
    "weight": 600,
    "tracking": {
      "desktop": -1,
      "mobile": -1
    },
    "underline": false
  },
  {
    "figma": "heading/2xl",
    "utility": "type-heading-2xl",
    "description": "font-heading text-2xl font-semibold tracking-tight · 24/32 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 24,
      "mobile": 24
    },
    "lineHeight": {
      "desktop": 32,
      "mobile": 32
    },
    "weight": 600,
    "tracking": {
      "desktop": -0.5,
      "mobile": -0.5
    },
    "underline": false
  },
  {
    "figma": "heading/xl",
    "utility": "type-heading-xl",
    "description": "font-heading text-xl font-semibold · 20/28 · Funnel Sans SemiBold.",
    "family": "Funnel Sans",
    "size": {
      "desktop": 20,
      "mobile": 20
    },
    "lineHeight": {
      "desktop": 28,
      "mobile": 28
    },
    "weight": 600,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/base/normal",
    "utility": "type-text-base-normal",
    "description": "text-base font-normal · 16/24 · Inter Regular.",
    "family": "Inter",
    "size": {
      "desktop": 16,
      "mobile": 16
    },
    "lineHeight": {
      "desktop": 24,
      "mobile": 24
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/base/medium",
    "utility": "type-text-base-medium",
    "description": "text-base font-medium · 16/24 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 16,
      "mobile": 16
    },
    "lineHeight": {
      "desktop": 24,
      "mobile": 24
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/base/semibold",
    "utility": "type-text-base-semibold",
    "description": "text-base font-semibold · 16/24 · Inter Semi Bold.",
    "family": "Inter",
    "size": {
      "desktop": 16,
      "mobile": 16
    },
    "lineHeight": {
      "desktop": 24,
      "mobile": 24
    },
    "weight": 600,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/base/link",
    "utility": "type-text-base-link",
    "description": "text-base font-medium underline underline-offset-4 · 16/24 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 16,
      "mobile": 16
    },
    "lineHeight": {
      "desktop": 24,
      "mobile": 24
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": true
  },
  {
    "figma": "text/sm/normal",
    "utility": "type-text-sm-normal",
    "description": "text-sm font-normal · 14/20 · Inter Regular.",
    "family": "Inter",
    "size": {
      "desktop": 14,
      "mobile": 14
    },
    "lineHeight": {
      "desktop": 20,
      "mobile": 20
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/sm/medium",
    "utility": "type-text-sm-medium",
    "description": "text-sm font-medium · 14/20 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 14,
      "mobile": 14
    },
    "lineHeight": {
      "desktop": 20,
      "mobile": 20
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/sm/semibold",
    "utility": "type-text-sm-semibold",
    "description": "text-sm font-semibold · 14/20 · Inter Semi Bold.",
    "family": "Inter",
    "size": {
      "desktop": 14,
      "mobile": 14
    },
    "lineHeight": {
      "desktop": 20,
      "mobile": 20
    },
    "weight": 600,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/sm/link",
    "utility": "type-text-sm-link",
    "description": "text-sm font-medium underline underline-offset-4 · 14/20 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 14,
      "mobile": 14
    },
    "lineHeight": {
      "desktop": 20,
      "mobile": 20
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": true
  },
  {
    "figma": "text/xs/normal",
    "utility": "type-text-xs-normal",
    "description": "text-xs font-normal · 12/16 · Inter Regular.",
    "family": "Inter",
    "size": {
      "desktop": 12,
      "mobile": 12
    },
    "lineHeight": {
      "desktop": 16,
      "mobile": 16
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/xs/medium",
    "utility": "type-text-xs-medium",
    "description": "text-xs font-medium · 12/16 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 12,
      "mobile": 12
    },
    "lineHeight": {
      "desktop": 16,
      "mobile": 16
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/xs/semibold",
    "utility": "type-text-xs-semibold",
    "description": "text-xs font-semibold · 12/16 · Inter Semi Bold.",
    "family": "Inter",
    "size": {
      "desktop": 12,
      "mobile": 12
    },
    "lineHeight": {
      "desktop": 16,
      "mobile": 16
    },
    "weight": 600,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/xs/link",
    "utility": "type-text-xs-link",
    "description": "text-xs font-medium underline underline-offset-4 · 12/16 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 12,
      "mobile": 12
    },
    "lineHeight": {
      "desktop": 16,
      "mobile": 16
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": true
  },
  {
    "figma": "text/2xs/normal",
    "utility": "type-text-2xs-normal",
    "description": "text-2xs font-normal · 10/14 · Inter Regular.",
    "family": "Inter",
    "size": {
      "desktop": 10,
      "mobile": 10
    },
    "lineHeight": {
      "desktop": 14,
      "mobile": 14
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/2xs/medium",
    "utility": "type-text-2xs-medium",
    "description": "text-2xs font-medium · 10/14 · Inter Medium.",
    "family": "Inter",
    "size": {
      "desktop": 10,
      "mobile": 10
    },
    "lineHeight": {
      "desktop": 14,
      "mobile": 14
    },
    "weight": 500,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "text/2xs/semibold",
    "utility": "type-text-2xs-semibold",
    "description": "text-2xs font-semibold · 10/14 · Inter Semi Bold.",
    "family": "Inter",
    "size": {
      "desktop": 10,
      "mobile": 10
    },
    "lineHeight": {
      "desktop": 14,
      "mobile": 14
    },
    "weight": 600,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "code/sm",
    "utility": "type-code-sm",
    "description": "font-mono text-sm · 14/20 · JetBrains Mono Regular.",
    "family": "JetBrains Mono",
    "size": {
      "desktop": 14,
      "mobile": 14
    },
    "lineHeight": {
      "desktop": 20,
      "mobile": 20
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  },
  {
    "figma": "code/xs",
    "utility": "type-code-xs",
    "description": "font-mono text-xs · 12/16 · JetBrains Mono Regular.",
    "family": "JetBrains Mono",
    "size": {
      "desktop": 12,
      "mobile": 12
    },
    "lineHeight": {
      "desktop": 16,
      "mobile": 16
    },
    "weight": 400,
    "tracking": {
      "desktop": 0,
      "mobile": 0
    },
    "underline": false
  }
] as const

export const fontFamilies = [
  {
    "figma": "font-family/heading",
    "cssVar": "--font-heading",
    "utility": "font-heading",
    "family": "Funnel Sans",
    "description": "Custom font-heading. Display and headings (Funnel Sans)."
  },
  {
    "figma": "font-family/sans",
    "cssVar": "--font-sans",
    "utility": "font-sans",
    "family": "Inter",
    "description": "Tailwind font-sans. Body and UI text (Inter)."
  },
  {
    "figma": "font-family/mono",
    "cssVar": "--font-mono",
    "utility": "font-mono",
    "family": "JetBrains Mono",
    "description": "Tailwind font-mono. Code (JetBrains Mono)."
  }
] as const

export const spacing = [
  {
    "figma": "spacing/4xs",
    "code": "calc(var(--spacing) * 0.5)",
    "utility": "p-0.5 · gap-0.5",
    "responsive": false,
    "desktop": 2,
    "mobile": 2,
    "description": "2px = Tailwind 0.5 (e.g. p-0.5, gap-0.5). Mobile 2px."
  },
  {
    "figma": "spacing/3xs",
    "code": "calc(var(--spacing) * 1)",
    "utility": "p-1 · gap-1",
    "responsive": false,
    "desktop": 4,
    "mobile": 4,
    "description": "4px = Tailwind 1 (e.g. p-1, gap-1). Mobile 4px."
  },
  {
    "figma": "spacing/3xs-plus",
    "code": "calc(var(--spacing) * 1.5)",
    "utility": "p-1.5 · gap-1.5",
    "responsive": false,
    "desktop": 6,
    "mobile": 6,
    "description": ""
  },
  {
    "figma": "spacing/2xs",
    "code": "calc(var(--spacing) * 2)",
    "utility": "p-2 · gap-2",
    "responsive": false,
    "desktop": 8,
    "mobile": 8,
    "description": "8px = Tailwind 2 (e.g. p-2, gap-2). Mobile 8px."
  },
  {
    "figma": "spacing/2xs-plus",
    "code": "calc(var(--spacing) * 2.5)",
    "utility": "p-2.5 · gap-2.5",
    "responsive": false,
    "desktop": 10,
    "mobile": 10,
    "description": ""
  },
  {
    "figma": "spacing/xs",
    "code": "calc(var(--spacing) * 3)",
    "utility": "p-3 · gap-3",
    "responsive": false,
    "desktop": 12,
    "mobile": 12,
    "description": "12px = Tailwind 3 (e.g. p-3, gap-3). Mobile 12px."
  },
  {
    "figma": "spacing/sm",
    "code": "calc(var(--spacing) * 4)",
    "utility": "p-4 · gap-4",
    "responsive": false,
    "desktop": 16,
    "mobile": 16,
    "description": "16px = Tailwind 4 (e.g. p-4, gap-4). Mobile 16px."
  },
  {
    "figma": "spacing/md",
    "code": "calc(var(--spacing) * 5)",
    "utility": "p-5 · gap-5",
    "responsive": false,
    "desktop": 20,
    "mobile": 20,
    "description": "20px = Tailwind 5 (e.g. p-5, gap-5). Mobile 20px."
  },
  {
    "figma": "spacing/lg",
    "code": "var(--space-lg)",
    "utility": "p-(--space-lg)",
    "responsive": true,
    "desktop": 24,
    "mobile": 20,
    "description": "24px = Tailwind 6 (e.g. p-6, gap-6). Mobile 20px."
  },
  {
    "figma": "spacing/xl",
    "code": "var(--space-xl)",
    "utility": "p-(--space-xl)",
    "responsive": true,
    "desktop": 32,
    "mobile": 24,
    "description": "32px = Tailwind 8 (e.g. p-8, gap-8). Mobile 24px."
  },
  {
    "figma": "spacing/2xl",
    "code": "var(--space-2xl)",
    "utility": "p-(--space-2xl)",
    "responsive": true,
    "desktop": 40,
    "mobile": 32,
    "description": "40px = Tailwind 10 (e.g. p-10, gap-10). Mobile 32px."
  },
  {
    "figma": "spacing/3xl",
    "code": "var(--space-3xl)",
    "utility": "p-(--space-3xl)",
    "responsive": true,
    "desktop": 48,
    "mobile": 36,
    "description": "48px = Tailwind 12 (e.g. p-12, gap-12). Mobile 36px."
  },
  {
    "figma": "spacing/4xl",
    "code": "var(--space-4xl)",
    "utility": "p-(--space-4xl)",
    "responsive": true,
    "desktop": 56,
    "mobile": 40,
    "description": "56px = Tailwind 14 (e.g. p-14, gap-14). Mobile 40px."
  }
] as const

export const radii = [
  {
    "figma": "radius/none",
    "utility": "rounded-none",
    "code": "var(--radius-none)",
    "value": 0,
    "mobile": 0,
    "description": "Tailwind rounded-none (0px desktop). shadcn: 0."
  },
  {
    "figma": "radius/2xs",
    "utility": "rounded-2xs",
    "code": "calc(var(--radius) - 6px)",
    "value": 2,
    "mobile": 2,
    "description": ""
  },
  {
    "figma": "radius/sm",
    "utility": "rounded-sm",
    "code": "calc(var(--radius) - 4px)",
    "value": 4,
    "mobile": 4,
    "description": "Tailwind rounded-sm (4px desktop). shadcn: calc(var(--radius) - 4px)."
  },
  {
    "figma": "radius/md",
    "utility": "rounded-md",
    "code": "calc(var(--radius) - 2px)",
    "value": 6,
    "mobile": 6,
    "description": "Tailwind rounded-md (6px desktop). shadcn: calc(var(--radius) - 2px)."
  },
  {
    "figma": "radius/base",
    "utility": "rounded-base",
    "code": "var(--radius)",
    "value": 8,
    "mobile": 8,
    "description": ""
  },
  {
    "figma": "radius/lg",
    "utility": "rounded-lg",
    "code": "var(--radius)",
    "value": 8,
    "mobile": 8,
    "description": "Tailwind rounded-lg (8px desktop). shadcn: var(--radius) — this is --radius."
  },
  {
    "figma": "radius/xl",
    "utility": "rounded-xl",
    "code": "calc(var(--radius) + 4px)",
    "value": 12,
    "mobile": 12,
    "description": "Tailwind rounded-xl (12px desktop). shadcn: calc(var(--radius) + 4px)."
  },
  {
    "figma": "radius/2xl",
    "utility": "rounded-2xl",
    "code": "calc(var(--radius) + 8px)",
    "value": 16,
    "mobile": 16,
    "description": "Tailwind rounded-2xl (16px desktop). shadcn: calc(var(--radius) + 8px)."
  },
  {
    "figma": "radius/full",
    "utility": "rounded-full",
    "code": "calc(infinity * 1px)",
    "value": 9999,
    "mobile": 9999,
    "description": "Tailwind rounded-full (80px desktop). shadcn: 9999px."
  }
] as const

export const effects = [
  {
    "figma": "shadow/xs",
    "utility": "shadow-xs",
    "css": "0 1px 2px 0 var(--shadow-color-soft)",
    "description": "shadow-xs · Inputs, selects, checkboxes, radio buttons and outline buttons. · 0 1px 2px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/sm",
    "utility": "shadow-sm",
    "css": "0 1px 4px 0 var(--shadow-color-soft)",
    "description": "shadow-sm · Cards, chat attachments, chips and the toggle handle. · 0 1px 4px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/md",
    "utility": "shadow-md",
    "css": "0 2px 8px 0 var(--shadow-color-medium)",
    "description": "shadow-md · Hovered cards and tooltips. · 0 2px 8px 0px rgb(0 0 0 / 0.16)"
  },
  {
    "figma": "shadow/lg",
    "utility": "shadow-lg",
    "css": "0 8px 24px 0 var(--shadow-color-medium)",
    "description": "shadow-lg · Dropdowns, popovers, hover cards and floating toolbars. · 0 8px 24px 0px rgb(0 0 0 / 0.16)"
  },
  {
    "figma": "shadow/xl",
    "utility": "shadow-xl",
    "css": "0 1px 3px 0 var(--shadow-color-soft), 0 8px 28px -8px var(--shadow-color-strong)",
    "description": "shadow-xl · Toasts and hovered event cards. · 0 8px 28px -8px rgb(0 0 0 / 0.24), 0 1px 3px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/2xl",
    "utility": "shadow-2xl",
    "css": "0 16px 64px 0 var(--shadow-color-strong)",
    "description": "shadow-2xl · Modals, drawers and sheets. · 0 16px 64px 0px rgb(0 0 0 / 0.24)"
  },
  {
    "figma": "shadow/inner",
    "utility": "inset-shadow-xs",
    "css": "inset 0 1px 2px 0 var(--shadow-color-soft)",
    "description": "inset-shadow-xs · Input wells and toggle tracks. · inset 0 1px 2px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/top",
    "utility": "shadow-top",
    "css": "0 -4px 12px 0 var(--shadow-color-soft)",
    "description": "shadow-top (custom) · Casts upward: sticky footers, composer docks, modal footers. · 0 -4px 12px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/bottom",
    "utility": "shadow-bottom",
    "css": "0 4px 12px 0 var(--shadow-color-soft)",
    "description": "shadow-bottom (custom) · Casts downward: sticky headers and top bars. · 0 4px 12px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "shadow/drag",
    "utility": "shadow-drag",
    "css": "0 1px 3px 0 var(--shadow-color-soft), 0 6px 24px -6px var(--shadow-color-medium)",
    "description": "shadow-drag (custom) · Items while being dragged. · 0 6px 24px -6px rgb(0 0 0 / 0.16), 0 1px 3px 0px rgb(0 0 0 / 0.08)"
  },
  {
    "figma": "focus/ring",
    "utility": "focus-ring",
    "css": "0 0 0 2px var(--background), 0 0 0 4px var(--ring)",
    "description": "ring-2 ring-ring ring-offset-2 ring-offset-background · Keyboard focus on every interactive element. Mode-aware. · 0 0px 0px 4px rgb(180 222 253 / 1), 0 0px 0px 2px rgb(255 255 255 / 1)"
  },
  {
    "figma": "elevation/raised",
    "utility": "shadow-elevation-raised",
    "css": "0 8px 24px 0 var(--shadow-color-medium)",
    "description": "Floating surfaces anchored to a trigger: Popover, Dropdown Menu, Menu, Combobox list, Date Picker, hover card. Same values as shadow/lg."
  },
  {
    "figma": "elevation/modal",
    "utility": "shadow-elevation-modal",
    "css": "0 1px 3px 0 var(--shadow-color-soft), 0 8px 28px -8px var(--shadow-color-strong)",
    "description": "Surfaces above a scrim: Dialog, Alert Dialog, Sheet, Drawer. Same values as shadow/xl."
  }
] as const

export const shell = [
  {
    "figma": "shell/container-height",
    "cssVar": "--shell-container-height",
    "full screen": 800,
    "side panel": 900,
    "popover": 640,
    "mobile": 720
  },
  {
    "figma": "shell/container-width",
    "cssVar": "--shell-container-width",
    "full screen": 1200,
    "side panel": 440,
    "popover": 400,
    "mobile": 390
  },
  {
    "figma": "shell/gap",
    "cssVar": "--shell-gap",
    "full screen": 24,
    "side panel": 20,
    "popover": 16,
    "mobile": 16
  },
  {
    "figma": "shell/header-height",
    "cssVar": "--shell-header-height",
    "full screen": 56,
    "side panel": 52,
    "popover": 48,
    "mobile": 52
  },
  {
    "figma": "shell/padding-x",
    "cssVar": "--shell-padding-x",
    "full screen": 32,
    "side panel": 16,
    "popover": 16,
    "mobile": 16
  },
  {
    "figma": "shell/padding-y",
    "cssVar": "--shell-padding-y",
    "full screen": 24,
    "side panel": 16,
    "popover": 12,
    "mobile": 16
  },
  {
    "figma": "shell/thread-max",
    "cssVar": "--shell-thread-max",
    "full screen": 768,
    "side panel": 408,
    "popover": 368,
    "mobile": 358
  },
  {
    "figma": "shell/widget-max",
    "cssVar": "--shell-widget-max",
    "full screen": 640,
    "side panel": 408,
    "popover": 368,
    "mobile": 358
  }
] as const
