// pnpm tokens:build — tokens/anvil.tokens.json → src/styles/tokens/*.css (Style Dictionary 5).
//
// Output (see CLAUDE.md → Tokens):
//   primitives.css  :root palette (referenced by the semantic files)
//   colors.css      :root / .light (light) · .dark · @theme inline --color-* registrations
//   typography.css  @theme static (desktop) · mobile @media override · text-style @utility type-*
//   dimensions.css  :root + @theme static (desktop) · mobile @media override · @theme inline radii
//   shell.css       :root / [data-shell="…"] for full screen · side panel · popover · mobile
//   effects.css     @theme inline shadows, inset shadow, elevation and focus ring
//
// Names come from each variable's Figma code syntax. Tokens whose code syntax is an expression
// (e.g. `calc(var(--spacing) * 4)`) are not declared; the build checks the expression still
// evaluates to the Figma value and fails if it does not.
import StyleDictionary from 'style-dictionary'

import {
  TOKENS_FILE,
  collectionOf,
  cssRefOrLiteral,
  cssValue,
  cssVarName,
  defaultModeOf,
  effectVarName,
  figmaExt,
  fontWeight,
  loadModel,
  modesOf,
  resolve,
  shadowCss,
  textStyleUtility,
} from './scripts/tokens/model.mjs'

const model = loadModel()
const MOBILE_QUERY = '@media (max-width: 767px)'
const HEADER =
  '/* Generated by `pnpm tokens:build` from tokens/anvil.tokens.json (pulled from Figma). Do not edit. */\n'

// Tailwind theme namespaces: tokens named into one are declared in @theme so utilities exist.
const TAILWIND_NAMESPACES = [
  '--font-',
  '--text-',
  '--tracking-',
  '--leading-',
  '--radius-',
  '--ease-',
  '--spacing-',
]
const inTailwindNamespace = (name) => TAILWIND_NAMESPACES.some((ns) => name.startsWith(ns))

const kebab = (s) => s.toLowerCase().replace(/\s+/g, '-')
const block = (selector, lines, indent = '') =>
  lines.length
    ? `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join('\n')}\n${indent}}\n`
    : ''

const modelTokens = (dictionary) =>
  dictionary.allTokens.map((t) => model.tokens.get(t.path.join('.'))).filter(Boolean)

/** `--name: value;` lines for one mode, deduplicated by name (two Figma paths may share one name). */
function declarations(tokens, mode, { only } = {}) {
  const seen = new Map()
  for (const token of tokens) {
    const name = cssVarName(token)
    if (!name || (only && !only(token, name))) continue
    const value = cssValue(model, token, mode)
    if (seen.has(name) && seen.get(name) !== value) {
      throw new Error(`${name} has two values in mode "${mode}": ${seen.get(name)} vs ${value}`)
    }
    seen.set(name, value)
  }
  return [...seen].map(([name, value]) => `${name}: ${value};`)
}

/** Lines that differ from the default mode (for the mobile @media override). */
function overrides(tokens, mode, defaultMode) {
  const base = new Set(declarations(tokens, defaultMode))
  return declarations(tokens, mode).filter((line) => !base.has(line))
}

// ── Expression check: calc() code syntax must still equal the Figma value ────────────────────
function checkExpressions(tokens) {
  const errors = []
  const radiusBase = model.tokens.get('dimensions.radius.base')
  for (const token of tokens) {
    const syntax = figmaExt(token).codeSyntax
    if (!syntax || cssVarName(token) || /^-?\d+(\.\d+)?px$/.test(syntax) || syntax.includes('infinity'))
      continue
    for (const mode of modesOf(model, token)) {
      const expr = syntax
        .replaceAll('var(--radius)', String(resolve(model, radiusBase, mode)))
        .replaceAll('var(--spacing)', '4') // Tailwind default --spacing: 0.25rem
        .replace(/^calc\((.*)\)$/, '$1')
        .replaceAll('px', '')
      if (!/^[\d\s.+\-*/()]+$/.test(expr)) {
        errors.push(`${token.name}: cannot evaluate code syntax "${syntax}"`)
        continue
      }
      const actual = Function(`return (${expr})`)()
      const expected = resolve(model, token, mode)
      if (actual !== expected)
        errors.push(`${token.name} (${mode}): "${syntax}" = ${actual}, Figma = ${expected}`)
    }
  }
  if (errors.length) throw new Error(`Code syntax no longer matches Figma values:\n  ${errors.join('\n  ')}`)
}

// ── Formats ───────────────────────────────────────────────────────────────────────────────

const formats = {
  'anvil/primitives': (tokens) => {
    const colors = tokens.filter((t) => t.$type === 'color')
    return block(':root', declarations(colors, 'value'))
  },

  'anvil/colors': (tokens) => {
    const [light, dark] = modesOf(model, tokens[0])
    const names = [...new Set(tokens.map(cssVarName).filter(Boolean))]
    return [
      block(':root,\n.light', declarations(tokens, light)),
      block('.dark', declarations(tokens, dark)),
      block(
        '@theme inline',
        names.map((n) => `--color-${n.slice(2)}: var(${n});`),
      ),
    ].join('\n')
  },

  // Desktop values in @theme static (Tailwind namespaces) or :root; mobile overrides in @media.
  'anvil/responsive': (tokens, extra = '') => {
    const defaultMode = defaultModeOf(model, tokens[0])
    const mobile = modesOf(model, tokens[0]).find((m) => m !== defaultMode)
    const themed = (_, name) => inTailwindNamespace(name)
    const plain = (_, name) => !inTailwindNamespace(name)
    const mobileLines = mobile ? overrides(tokens, mobile, defaultMode) : []
    return [
      block(':root', declarations(tokens, defaultMode, { only: plain })),
      block('@theme static', declarations(tokens, defaultMode, { only: themed })),
      mobileLines.length ? `${MOBILE_QUERY} {\n${block(':root', mobileLines, '  ')}}\n` : '',
      extra,
    ]
      .filter(Boolean)
      .join('\n')
  },

  'anvil/typography': (tokens) => {
    const variables = tokens.filter((t) => collectionOf(t) === 'typography')
    const styles = tokens.filter((t) => collectionOf(t) === 'text-styles')
    const utilities = styles.map((token) => {
      const v = token.$value
      const deco = figmaExt(token).textDecoration
      return block(`@utility ${textStyleUtility(token)}`, [
        `font-family: ${cssRefOrLiteral(model, v.fontFamily, (f) => `"${f}"`)};`,
        `font-size: ${cssRefOrLiteral(model, v.fontSize, (n) => `${n}px`)};`,
        `line-height: ${cssRefOrLiteral(model, v.lineHeight, (n) => (typeof n === 'object' ? `${n.value}px` : n))};`,
        `font-weight: ${cssRefOrLiteral(model, v.fontWeight, fontWeight)};`,
        `letter-spacing: ${cssRefOrLiteral(model, v.letterSpacing, (n) => (typeof n === 'object' ? `${n.value}px` : `${n}px`))};`,
        ...(deco === 'UNDERLINE' ? ['text-decoration-line: underline;'] : []),
        ...(deco === 'STRIKETHROUGH' ? ['text-decoration-line: line-through;'] : []),
      ])
    })
    return formats['anvil/responsive'](variables, `/* Figma text styles */\n${utilities.join('\n')}`)
  },

  'anvil/dimensions': (tokens) => {
    checkExpressions(tokens)
    // Radius utilities derive from --radius (code syntax), registered inline so a changed --radius
    // on any element re-rounds its children. --radius-none is a declared token instead.
    const radii = tokens
      .filter((t) => t.path[1] === 'radius' && cssVarName(t) !== `--radius-${t.path[2]}`)
      .map((t) => `--radius-${t.path[2]}: ${figmaExt(t).codeSyntax};`)
    return formats['anvil/responsive'](tokens, block('@theme inline', radii))
  },

  'anvil/shell': (tokens) => {
    const modes = modesOf(model, tokens[0])
    const defaultMode = defaultModeOf(model, tokens[0])
    return modes
      .map((mode) => {
        const selector = `[data-shell="${kebab(mode)}"]`
        return block(mode === defaultMode ? `:root,\n${selector}` : selector, declarations(tokens, mode))
      })
      .join('\n')
  },

  'anvil/effects': (tokens) => {
    const lines = tokens.map((t) => `${effectVarName(t)}: ${shadowCss(model, t)};`)
    return block('@theme inline', lines)
  },
}

for (const [name, render] of Object.entries(formats)) {
  StyleDictionary.registerFormat({
    name,
    format: ({ dictionary }) => HEADER + '\n' + render(modelTokens(dictionary)),
  })
}

// Style Dictionary's own token names (used for its collision checks) are the full path;
// CSS names come from Figma code syntax inside the formats above.
StyleDictionary.registerTransform({
  name: 'name/anvil-path',
  type: 'name',
  transform: (token) => token.path.join('.'),
})

const byCollection =
  (...names) =>
  (token) =>
    names.includes(token.path[0])

const sd = new StyleDictionary({
  source: [TOKENS_FILE],
  usesDtcg: true,
  log: { verbosity: 'default', warnings: 'error' },
  platforms: {
    css: {
      transforms: ['name/anvil-path'],
      buildPath: 'src/styles/tokens/',
      files: [
        { destination: 'primitives.css', format: 'anvil/primitives', filter: byCollection('primitives') },
        { destination: 'colors.css', format: 'anvil/colors', filter: byCollection('colors') },
        {
          destination: 'typography.css',
          format: 'anvil/typography',
          filter: byCollection('typography', 'text-styles'),
        },
        { destination: 'dimensions.css', format: 'anvil/dimensions', filter: byCollection('dimensions') },
        { destination: 'shell.css', format: 'anvil/shell', filter: byCollection('shell') },
        { destination: 'effects.css', format: 'anvil/effects', filter: byCollection('effects') },
      ],
    },
  },
})

await sd.buildAllPlatforms()

// Effect descriptions in Figma start with the utility they map to ("shadow-xs · …"); warn on drift.
for (const token of model.tokens.values()) {
  if (collectionOf(token) !== 'effects') continue
  const named = token.$description?.match(/^([a-z0-9-]+)(?: \(custom\))? ·/)?.[1]
  const ours = effectVarName(token).slice(2)
  if (named && named !== ours) console.warn(`⚠ ${token.name}: Figma names "${named}", build emits "${ours}"`)
}
const skipped = [...model.tokens.values()].filter(
  (t) => collectionOf(t) !== 'effects' && collectionOf(t) !== 'text-styles' && !figmaExt(t).codeSyntax,
)
if (skipped.length)
  console.warn(`⚠ No code syntax in Figma (not emitted): ${skipped.map((t) => t.name).join(', ')}`)
